### ISSUE TITLE
Feature request: Adopt the script for MiXCR 2

### ISSUE THREAD

**Issue by eodus** [AstraZeneca-NGS/tcrbiter#2]
In MiXCR 2 the command line argument -l/--loci has been replaced with -c/--chains. Thus, it would be appreciated to update the script to make it compatible.

**Comment by roryk** [comment]
Thanks Alexander-- I swapped over the call to -l, but I get different results. I'm chatting with the folks that wrote tcrBiter tomorrow and I'll show them the different results and see what they think. Right now you can install mixcr1.7 via homebrew, if you are using that:

```
brew install milaboratory/all/mixcr17
```

that will get you 1.7, which should work ok.

**Comment by eodus** [comment]
As I know, MiXCR authors changed a lot in version 2. They even implemented a new alignment algorithm. So, reproduceability problems are not surprising. But anyway, I would likely suggest to use the latest version, since version 1.* seems to be abandoned.

**Comment by roryk** [comment]
Hi @eodus,

Sorry I didn't tag you in the commit-- I added support for mixcr2 a while ago, so it should be all set.
