### ISSUE TITLE
Feature request: Stop the pipeline when any stage fails

### ISSUE THREAD

**Issue by eodus** [AstraZeneca-NGS/tcrbiter#3]
For this moment the pipeline does not stop even if, for example, BLAST fails.

**Comment by roryk** [comment]
Thanks for the good suggestion, Alexander. I added a bunch of checks for the return code of the command line calls which catches most of the errors. mixcr 1.7 doesn't return a non-zero exit code when it errors out so those steps will pass for now but this should help with the other ones.

**Comment by eodus** [comment]
Nice, thanks! Considering to MiXCR, it seems as a bug of version 1.7 that is already fixed in later versions. At least, 2.1.1 (the latest one) returns non-zero code when it fails.

**Comment by roryk** [comment]
Thanks, that is good to know, hopefully we'll get the thumbs up for switching over to 2.1.1.
